### ISSUE TITLE
Checklist para próxima prática de Git

### ISSUE THREAD

**Issue by AndersonG2021** [AndersonG2021/GCMS-Anderson-Guilherme#2]
@ramidedantas 

- [x] o Instalar Git localmente
- [x] o Criar projeto local
- [x] o Criar repositório local e realizar commits
- [x] o Subir alterações para o repositório remoto
- [x] o Fazer alterações no repositório da turma
